version: 2

references:
  npm_install_update: &npm_install_update
    run:
      name: npm-update-and-install
      command: |
        sudo npm install -g npm@latest
        npm install
        npm run postinstall

jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *npm_install_update
      - run:
          name: pre-publish
          command: npm run vscode:prepublish
  test:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *npm_install_update
      - run:
          name: build
          command: npm run build
      - run:
          name: Test
          command: npm run test:unit:ci
  publish:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - *npm_install_update
      - run:
          name: install VS Code Extension Manager
          command: npm i vsce
      - run:
          name: publish to marketplace
          command: npx vsce publish -p ${VSTOKEN}

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - test:
          requires:
            - build
      - publish:
          requires:
            - build
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
